// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package db

import (
	"database/sql"
)

type Update struct {
	ID          int64
	Description string
	Archived    bool
	CreatedAt   sql.NullTime
	UpdatedAt   sql.NullTime
}
